name = "Flase"
authors = ["Simon Christ <Simon.Christ@gmx.de>"]
uuid = "e858aef0-9fb5-5af5-8432-d2c1ef8645cd"
version = "0.1.0"

[deps]
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
